image: docker:latest
services:
  - docker:dind

variables:
  CONTAINER_GITLAB_IMAGE: registry.gitlab.com/priambudi/bagas-findcomputer:latest
  CONTAINER_HEROKU_IMAGE: registry.heroku.com/bagas-findcomputer:latest


stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "cd backend && mvn package -B"
  artifacts:
    paths:
      - backend/target/*.jar

docker-build:
  stage: package
  script:
  - docker build -t $CONTAINER_GITLAB_IMAGE .
  - docker login -u gitlab-ci-token -p $GITLAB_CI_TOKEN registry.gitlab.com
  - docker push $CONTAINER_GITLAB_IMAGE

deploy-to-heroku:
  stage: deploy
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $GITLAB_CI_TOKEN registry.gitlab.com
    - docker pull $CONTAINER_GITLAB_IMAGE
    - docker login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com
    - docker tag $CONTAINER_GITLAB_IMAGE $CONTAINER_HEROKU_IMAGE
    - docker push $CONTAINER_HEROKU_IMAGE
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web --app bagas-findcomputer