image: docker:latest
services:
  - docker:dind

variables:
  CONTAINER_GITLAB_IMAGE: registry.gitlab.com/priambudi/bagas-findcomputer:latest
  CONTAINER_HEROKU_IMAGE: registry.heroku.com/bagas-findcomputer
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  BACKEND_SSH: ubuntu@54.179.1.245

stages:
  - build
  - test
  - deploy
  - post-deploy-test

springboot-build:
  image: maven:3-jdk-8
  stage: build
  script: "cd backend && mvn package -B"
  artifacts:
    paths:
      - backend/target/FindComputer-0.0.1-SNAPSHOT.jar
  
gatsby-build:
  image: node:latest
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run-script build
  artifacts:
    paths:
      - frontend/public

springboot-test:
  image: maven:3-jdk-8
  stage: test
  script: "cd backend && mvn clean test -P unit-test"

docker-build-deploy:
  stage: deploy
  script:
    - docker build -f Dockerfile --iidfile imageid.txt -t $CONTAINER_GITLAB_IMAGE .
    - docker login -u gitlab-ci-token -p $GITLAB_CI_TOKEN registry.gitlab.com
    - docker push $CONTAINER_GITLAB_IMAGE

springboot-ec2-deploy:
  image: alpine
  stage: deploy
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no $BACKEND_SSH sudo rm -R FindComputer-0.0.1-SNAPSHOT.jar
    - scp -o StrictHostKeyChecking=no backend/target/FindComputer-0.0.1-SNAPSHOT.jar $BACKEND_SSH:~
    - ssh -o StrictHostKeyChecking=no $BACKEND_SSH killall java || true
    - ssh -o StrictHostKeyChecking=no $BACKEND_SSH killall java || true
    - ssh -o StrictHostKeyChecking=no $BACKEND_SSH "nohup java -Xmx300m -Xss512k -Djava.security.egd\=file:/dev/./urandom -jar FindComputer-0.0.1-SNAPSHOT.jar 1>/dev/null 2>/dev/null &"
#     ps | grep java-fullstack | awk '{print $1}' | xargs kill -9 || true
# env SERVER.PORT=8081 nohup java -jar ./target/java-fullstack-1.0-SNAPSHOT.jar &
    # sudo scp -i "skripsi.pem" ./FindComputer-0.0.1-SNAPSHOT.jar ubuntu@54.179.1.245:~
    # docker build -t registry.gitlab.com/priambudi/bagas-findcomputer:latest .
    # docker login -u gitlab-ci-token -p pSGDGJtAqDqsm3E_x8ce registry.gitlab.com
    # docker pull registry.gitlab.com/priambudi/bagas-findcomputer:latest
    # docker run registry.gitlab.com/priambudi/bagas-findcomputer:latest
gatsby-deploy:
  image: python:latest
  stage: deploy
  script:
    - cd frontend
    - pip install awscli
    - aws s3 sync public s3://find-computer/

e2e_tests:
  image:
    name: testcafe/testcafe
    entrypoint: ["/bin/sh", "-c"]
  stage: post-deploy-test
  script:
    - cd frontend
    - /opt/testcafe/docker/testcafe-docker.sh firefox:headless,chromium ./tests/