image: docker:latest
services:
  - docker:dind

variables:
  CONTAINER_GITLAB_IMAGE: registry.gitlab.com/priambudi/bagas-findcomputer:latest
  CONTAINER_HEROKU_IMAGE: registry.heroku.com/bagas-findcomputer
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

stages:
  - build
  - test
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "cd backend && mvn package -B"
  artifacts:
    paths:
      - backend/target/FindComputer-0.0.1-SNAPSHOT.jar
  
gatsby-build:
  image: node:latest
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run-script build
  artifacts:
    paths:
      - frontend/public

gatsby-test:
  image: node:latest
  stage: test
  script: "cd frontend && npm test"

springboot-test:
  image: maven:3-jdk-8
  stage: test
  script: "cd backend && mvn clean test -P unit-test"

docker-build-deploy:
  stage: deploy
  script:
    - docker build -f Dockerfile --iidfile imageid.txt -t $CONTAINER_GITLAB_IMAGE .
    - docker login -u gitlab-ci-token -p $GITLAB_CI_TOKEN registry.gitlab.com
    - docker push $CONTAINER_GITLAB_IMAGE

gatsby-deploy:
  image: python:latest
  stage: deploy
  script:
    - cd frontend
    - pip install awscli
    - aws s3 sync public s3://find-computer/
