apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bagas-findcomputer
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: bagas-findcomputer
    spec:
      containers:
      - name: bagas-findcomputer
        image: registry.gitlab.com/priambudi/bagas-findcomputer
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: registry.gitlab.com